adminapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('adminlogin/',views.admin_login,name='admin_login'),
    path('',views.admin_home,name='admin_home'),
    path('admin_logout/',views.admin_logout,name='admin_logout'),
    path('user_manage/',views.user_manage,name='user_manage'),
    path('blockUser/<int:id>/', views.blockUser, name='blockUser'),

    path('categories/', views.categories, name='categories'),
    path('addCategory/', views.addCategory, name='addCategory'),
    path('<str:slug>/editCategory/', views.editCategory, name='editCategory'),
    path('<str:slug>/deleteCategory/', views.deleteCategory, name='deleteCategory'),
  
    path('<str:category_slug>/subCategories/', views.subCategories, name='subCategories'),
    path('<str:category_slug>/addsubcategory/', views.addSubCategory, name='addSubCategory'),
    path('<str:slug>/editSubCategory/', views.editSubCategory, name='editSubCategory'),
    path('<str:slug>/deleteSubCategory/', views.deleteSubCategory, name='deleteSubCategory'),
    
    path('products/', views.products, name='products'),
    path('<int:id>/deleteProduct/', views.deleteProduct, name='deleteProduct'),
    path('<int:id>/editProduct/', views.editProduct, name='editProduct'),
    path('addProduct/', views.addProduct, name='addProduct'),
  
    path('products/product_variations/', views.product_variations, name='product_variations'),
    path('products/product_variations/add_product_variation/', views.add_product_variation, name='add_product_variation'),
    path('products/product_variations/<int:id>/edit_variation', views.edit_product_variation, name='edit_product_variation'),
    path('products/product_variations/<int:id>/delete_variation', views.delete_product_variation, name='delete_product_variation'),

    path('coupon_offers/',views.coupons,name="coupons"),
    path('add_coupon_offers/',views.add_coupon,name="add_coupon"),
    path('edit_coupon_offers/<int:id>/',views.edit_coupon,name="edit_coupon"),
    path('delete_coupon/<int:id>/',views.delete_coupon,name="delete_coupon"),
    
    path('reviews/',views.reviews,name="reviews"),
    path('add_reviews/',views.add_reviews,name="add_reviews"),
    path('delete_reviews/<int:id>/',views.delete_reviews,name="delete_reviews"),
  

    path('orders/', views.orders, name='orders'),
    path('update_order/<int:id>',views.update_order,name="update_order"),
  
    path('sales_report/',views.sales_report,name="sales_report"),
    path('sales_report_month/<int:id>',views.sales_report_month,name="sales_report_month"),
    path("sales_report_year/<int:id>",views.sales_report_year,name='sales_report_year'),
        
    path('pdf_report/<str:start_date>//<str:end_date>/', views.pdf_report, name='pdf_report'),  
    path('excel_report/<str:start_date>//<str:end_date>/', views.excel_report, name='excel_report'),


    path('category_offers/', views.category_offers, name='category_offers'),
    path('add_category_offer/', views.add_category_offer, name='add_category_offer'),
    path('delete_category_offer/<int:id>/', views.delete_category_offer, name='delete_category_offer'),

    path('product_offers/', views.product_offers, name='product_offers'),
    path('add_product_offer/', views.add_product_offer, name='add_product_offer'),
    path('delete_product_offer/<int:id>/', views.delete_product_offer, name='delete_product_offer'),

  
    path('banner',views.banner,name='banner'),
    path('add_banner/',views.add_banner,name='add_banner'),
    path('select_banner/<int:id>',views.select_banner,name='select_banner'),
    path('deselect_banner/<int:id>',views.deselect_banner,name='deselect_banner'),
    path('remove_banner/<int:id>',views.remove_banner,name='remove_banner'),

 
]

case/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.views.static import serve
from django.contrib import admin

urlpatterns = [
        path("admin/", admin.site.urls),

    path('', include('shop.urls')),
    path('adminn/', include('adminapp.urls')),
    path('accounts/', include('account.urls')),
    path('cart/', include('carts.urls')),
    path('orders/', include('orders.urls')),
    path('wishlist/', include('wishlist.urls')),
]

if settings.DEBUG:
    urlpatterns += [
        path('media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT}),
        path('static/<path:path>', serve, {'document_root': settings.STATIC_ROOT}),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('place_order/', views.place_order, name='place_order'),
  path('payments/', views.payments, name='payments'),
  path('razorpay/', views.razorpay, name='razorpay'),
  
  path('payments_completed/',views.payments_completed,name = 'payments_completed'),
  
  path("cash_on_delivery/<int:id>/",views.cash_on_delivery,name='cash_on_delivery'),
  
  path("cancel_order/<int:id>/",views.cancel_order,name='cancel_order'),
  path("return_order/<int:id>/",views.return_order,name='return_order'),
  
  path("coupon/",views.coupon,name='coupon'),
 
]

orders/models.py
from django.db import models
from account.models import Account
from shop.models import Product, Variation
from django.core.validators import MinValueValidator,MaxValueValidator
from django.utils import timezone
import pytz

# Create your models here.

class Payment(models.Model):
    user    =  models.ForeignKey(Account,on_delete=models.CASCADE)
    payment_id =   models.CharField(max_length=100)
    order_id = models.CharField(max_length=100,blank=True)
    payment_method = models.CharField(max_length=100)
    amount_paid     = models.CharField(max_length=100) #this is total amount paid
    created_at = models.DateTimeField(auto_now_add=True)
    status         = models.BooleanField(default=False)

    def __str__(self):
        return self.payment_id
      
class Address(models.Model):
    user = models.ForeignKey(Account,on_delete=models.CASCADE)
    first_name = models.CharField(max_length=50)
    last_name   = models.CharField(max_length=50)
    phone = models.CharField(max_length=15)
    email = models.EmailField(max_length=50)
    address_line1 = models.CharField(max_length=50)
    address_line2 = models.CharField(max_length=50,null=True)
    state =   models.CharField(max_length=50)
    district =   models.CharField(max_length=50)
    city =   models.CharField(max_length=50,blank=True)
    pincode =   models.IntegerField(default=0)
    order_note = models.CharField(max_length=100, blank=True)
    
    def full_name(self):
        return f"{self.first_name} {self.last_name}"

    def address(self):
        return f"{self.address_line1} {self.address_line2}"

    def __str__(self):
        return self.first_name

class Order(models.Model):
    STATUS = (
        ('Order Confirmed', 'Order Confirmed'),
        ('Shipped',"Shipped"),
        ('Out for delivery',"Out for delivery"),
        ('Delivered', 'Delivered'),
        ('Cancelled','Cancelled'),
        ('Returned','Returned'),
    )

    user = models.ForeignKey(Account, on_delete=models.SET_NULL,null=True)
    payment= models.ForeignKey(Payment,on_delete=models.SET_NULL,blank=True,null=True)
    order_number = models.CharField(max_length=30)
    first_name = models.CharField(max_length=50, default='')
    last_name   = models.CharField(max_length=50, default='')
    phone = models.CharField(max_length=15, default='')
    email = models.EmailField(max_length=50, default='')
    address_line1 = models.CharField(max_length=50, default='')
    address_line2 = models.CharField(max_length=50,blank=True)
    state =   models.CharField(max_length=50, default='')
    district =   models.CharField(max_length=50, default='')
    city =   models.CharField(max_length=50, default='')
    pincode =   models.IntegerField(default=0)
    order_note = models.CharField(max_length=100, blank=True)
    order_total = models.FloatField()
    order_discount = models.FloatField(default=0)
    tax     = models.FloatField()
    status = models.CharField(max_length=50,choices=STATUS,default='Order Confirmed')
    ip = models.CharField(blank=True,max_length=20)
    is_ordered = models.BooleanField(default=False)
    is_returned = models.BooleanField(default=False)
    return_reason = models.CharField(max_length=50, blank=True)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.order_number
    
    def full_name(self):
        return f'{self.first_name} {self.last_name}'
    
    def full_address(self):
        return f'{self.address_line1} {self.address_line2}'
      
class OrderProduct(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='user_order_page')
    payment = models.ForeignKey(Payment,on_delete=models.SET_NULL,blank=True,null=True)
    user = models.ForeignKey(Account,on_delete=models.CASCADE)
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    variations = models.ManyToManyField(Variation,blank=True)
    quantity = models.IntegerField()
    product_price = models.FloatField()
    ordered = models.BooleanField(default=False)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.product.product_name
    
class Coupon(models.Model):
    code = models.CharField(max_length=50,unique=True)
    discount = models.IntegerField(validators = [MinValueValidator(0),MaxValueValidator(30)])
    min_value = models.IntegerField(validators = [MinValueValidator(0)])
    valid_from = models.DateTimeField(auto_now_add=True)
    valid_at = models.DateField()
    active = models.BooleanField(default=False)
    def __str__(self):
        return self.code
    
class UserCoupon(models.Model):
    user =  models.ForeignKey(Account,on_delete=models.CASCADE, null= True)
    coupon = models.ForeignKey(Coupon,on_delete = models.CASCADE, null = True)
    order  = models.ForeignKey(Order,on_delete=models.SET_NULL,null = True,related_name='order_coupon')
    used = models.BooleanField(default = False)
    def __str__(self):  
        return str(self.id)

shop/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from account.models import Account
from category.models import Category, Sub_Category

# Create your models here.

class Product(models.Model):
  
  UNIT = (('Piece', 'Piece'),('Combo', 'Combo'),)
  product_name = models.CharField(max_length=200, unique=True)
  slug = models.SlugField(max_length=255, unique=True)
  description = models.TextField(max_length=500, blank=True)
  price = models.IntegerField()
  product_offer = models.IntegerField(default = 0)
  unit = models.CharField(max_length=50,choices=UNIT,default='Piece')
  image_1 = models.ImageField(upload_to='photos/products', blank=False)
  image_2 = models.ImageField(upload_to='photos/products', blank=True)
  image_3 = models.ImageField(upload_to='photos/products', blank=True)
  image_4 = models.ImageField(upload_to='photos/products', blank=True)
  stock = models.IntegerField()
  is_available = models.BooleanField(default=True)
  is_featured = models.BooleanField(default=False)
  category = models.ForeignKey(Category, on_delete=models.CASCADE)
  sub_category = models.ForeignKey(Sub_Category, on_delete=models.CASCADE)
  created_date = models.DateTimeField(auto_now_add=True)
  modified_date = models.DateTimeField(auto_now=True)
  users_wishlist     =models.ManyToManyField(settings.AUTH_USER_MODEL,related_name='users_wishlist',blank=True)
  
  def get_url(self):
    return reverse('product_details', args=[self.category.slug, self.sub_category.slug, self.slug])
  
  def __str__(self):
    return self.product_name
  
  def offer_price(self):
    product_offer = int(self.price) - int(self.price) * int(self.product_offer) /100 
    category_offer = int(self.price) - int(self.price) * int(self.category.category_offer)/100
    if product_offer == int(self.price) and category_offer == int(self.price):
        return self.price
    if product_offer <= category_offer:
        return int(product_offer)
    else:
        return category_offer
  
class VariationManager(models.Manager):
  def sizes(self):
    return super(VariationManager, self).filter(variation_category='size', is_active=True)
  
variation_category_choice =  (
    ('size','size'),
)


class Variation(models.Model):
  product = models.ForeignKey(Product, on_delete=models.CASCADE)
  variation_category = models.CharField(max_length=100, choices=variation_category_choice)
  variation_value = models.CharField(max_length=100)
  is_active = models.BooleanField(default=True)
  created_date = models.DateTimeField(auto_now=True)
  
  objects = VariationManager()
  
  def __str__(self):
    return self.variation_value
  

  






#product review
RATING = (
  (1,'1'),
  (2,'2'),
  (3,'3'),
  (4,'4'),
  (5,'5'),
)
class ProductReview(models.Model):
   user = models.ForeignKey(Account, on_delete=models.CASCADE, null=True)
   product = models.ForeignKey(Product, on_delete=models.CASCADE)
   review_text = models.TextField(null=True)
   review_rating = models.CharField(choices=RATING, max_length=150)



class Banner(models.Model):
    
    banner_image =models.ImageField( upload_to='photos/banner', height_field=None, width_field=None, max_length=None,blank=True)
    
    is_selected = models.BooleanField(default=False)

adminapp/forms.py
from django import forms
from shop.models import Product, Variation , ProductReview
from category.models import Category, Sub_Category
from account.models import Account
from orders.models import Coupon
import datetime



class LoginForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control mb-3 mt-1 validate',}), max_length=100)
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control mt-1  validate',}), label="Password")

class UserForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ['first_name', 'last_name', 'email', 'phone_number', 'is_admin', 'is_staff', 'is_superadmin']
        
    def __init__(self, *args, **kwargs):
        super(UserForm,self).__init__(*args, **kwargs)
        self.fields['phone_number'].widget.attrs['maxlength'] = 10
        
        for field  in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

class ProductForm(forms.ModelForm):
    class Meta:
         model = Product
         fields = ['product_name', 'slug', 'description', 'price', 'unit', 'image_1', 'image_2', 'image_3', 'image_4', 'stock',
                      'is_available', 'is_featured', 'category', 'sub_category']
        
    def __init__(self, *args, **kwargs):
        super(ProductForm,self).__init__(*args, **kwargs)
        self.fields['price'].widget.attrs['min'] = 0
        self.fields['stock'].widget.attrs['min'] = 0
        self.fields['category'].widget.attrs['onchange'] = "getval(this);"

        for field  in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'


class VariationForm(forms.ModelForm):
    class Meta:
        model = Variation
        fields = ['product', 'variation_category', 'variation_value', 'is_active']
        
    def __init__(self, *args, **kwargs):
        super(VariationForm,self).__init__(*args, **kwargs)
        for field  in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'
                
class CategoryForm(forms.ModelForm):
    class Meta:
         model = Category
         fields = ['category_name', 'slug','description', 'cat_image',]
        
    def __init__(self, *args, **kwargs):
        super(CategoryForm,self).__init__(*args, **kwargs)
        for field  in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'
            
class SubCategoryForm(forms.ModelForm):
    class Meta:
         model = Sub_Category
         fields = ['sub_category_name', 'slug', 'description', 'category', 'is_featured',]
        
    def __init__(self, *args, **kwargs):
        super(SubCategoryForm,self).__init__(*args, **kwargs)
        for field  in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'


class DateInput(forms.DateInput):
    input_type = 'date'

class CouponForm(forms.ModelForm):
    class Meta:
        model = Coupon
        fields = ['code', 'discount','min_value','valid_at','active']
        widgets = {
                    'valid_at': DateInput(),
                    }
    def __init__(self, *args, **kwargs):
        super(CouponForm,self).__init__(*args, **kwargs)
        self.fields['valid_at'].widget.attrs['min'] = str(datetime.date.today())
        
        for field  in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'


    

orders/forms.py
from django import forms
from .models import Address, Order


class OrderForm(forms.ModelForm):
  class Meta:
    model = Order
    fields = ['first_name','last_name','phone','email','address_line1','address_line2','state','district','city','pincode', 'order_note']

templates/adminapp/addbanner.html
{% extends 'adminapp/adminbase.html' %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}
{% load static%}

{% block title%}
Add Banner
{%endblock%}

{% block navbar%}
<div class="navbar-nav w-100">
  <a href="{% url 'admin_home'%}" class="nav-item nav-link   "><i class="fa fa-tachometer-alt me-2"></i>Dashboard</a>
  <a href="{% url 'sales_report' %}" class="nav-item nav-link  "><i class="bi bi-archive me-2"></i>Sales Report</a>
  <a href="{% url 'products'%}" class="nav-item nav-link "><i class="fa fa-laptop me-2"></i>Products</a>
  <a href="{% url 'categories'%}" class="nav-item nav-link "><i class="fa fa-th me-2"></i>Categories</a>
  <a href="{% url 'user_manage'%}" class="nav-item nav-link "><i class="bi bi-person me-2"></i>Users</a>
  <a href="{% url 'orders'%}" class="nav-item nav-link"><i class="fa fa-table me-2"></i>Orders</a>
  <a href="{% url 'banner'%}" class="nav-item nav-link active"><i class="fa fa-table me-2"></i>Banners</a>
  <div class="nav-item dropdown">
    <a href="#" class="nav-link dropdown-toggle " data-bs-toggle="dropdown"><i class="far fa-file-alt me-2"></i>Offers</a>
    <div class="dropdown-menu bg-transparent border-0">
        <a href="{% url 'category_offers' %}" class="dropdown-item">Category Offers</a>
        <a href="{% url 'product_offers' %}" class="dropdown-item">Product Offers</a>
        <a href="{% url 'coupons'%}" class="dropdown-item">Coupons</a>
        
    </div>
</div>
</div>


{%endblock%}


{% block content%}

<div class="d-flex flex-column">
  <a href="{% url 'banner' %}" style="margin-left:10px;"> <button type="button" class="btn btn-outline-primary  " style="margin:auto;" >Back</button></a>
   
<form action="{% url 'add_banner' %}" method="POST" class="col-lg-6 uniForm" style="padding:2rem;margin:auto; " enctype="multipart/form-data">
  {% csrf_token %}
  <label class="col-sm-2 col-form-label" for="basic-default-company" >Image</label>
  
  <div class="col-sm-10">
    <input type="file" class="form-control" id="basic-default-company" name="image" accept="image/png, image/gif, image/jpeg, image/jpg, image/webp" id="imageInp3"  />
      
 </div>
 
  <button class='btn_1 btn btn-outline-success ' style=" margin-top:2rem;margin-left:13rem" type="submit" >Add</button>
</form>
</div>
 <!--........................... #crop guide................................ -->
 <script defer src="https://cdn.crop.guide/loader/l.js?c=JPHQRG"></script>
 
 
 <script>
     function checker(id){
       img = document.getElementById(id.id).value
       if(!img.match(/\.(jpg|jpeg|png|gif)$/)){
         swal("image should be jpg , jpeg , png")
         document.getElementById(id.id).value = "";
       }
 
   }
   </script>
 
 
 {% endblock %}

templates/adminapp/addsubcategory.html
{% extends 'adminapp/adminbase.html' %}
{% load static%}

{% block title%}
Sub Category
{%endblock%}

{% block navbar%}
<div class="navbar-nav w-100">
    <a href="{% url 'admin_home'%}" class="nav-item nav-link "><i class="fa fa-tachometer-alt me-2"></i>Dashboard</a>
    <a href="#" class="nav-item nav-link"><i class="bi bi-archive me-2"></i>Sales Report</a>
    <a href="" class="nav-item nav-link"><i class="fa fa-laptop me-2"></i>Products</a>
    <a href="#" class="nav-item nav-link active"><i class="fa fa-th me-2"></i>Categories</a>
    <a href="{% url 'user_manage'%}" class="nav-item nav-link "><i class="bi bi-person me-2"></i>Users</a>
    <a href="#" class="nav-item nav-link"><i class="fa fa-table me-2"></i>Orders</a>
    <div class="nav-item dropdown">
      <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"><i class="far fa-file-alt me-2"></i>Offers</a>
      <div class="dropdown-menu bg-transparent border-0">
          <a href="#" class="dropdown-item">Category Offers</a>
          <a href="" class="dropdown-item">Product Offers</a>
          <a href="" class="dropdown-item">Coupons</a>
      </div>
  </div>
  
</div>

{%endblock%}


{% block content%}
<div class="text-center mx-auto mt-2"  style="min-width: 22rem;">{% include 'includes/alerts.html' %}</div>

<div class="container mt-3" style="min-height: 33rem;">
    <h2 class="text-center text-white">Add Sub Category</h2>
    <form action="{% url 'addSubCategory' category.slug %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {% for message in messages %}
                     <h4 style="color: yellow;">{{message}}</h4>
                     {% endfor %}
  
      <div class="col form-group">
          <label >Sub Category Name </label><br>
          {{form.sub_category_name}}
      </div>
      <div class="col form-group">
          <label > Slug</label><br>
          {{form.slug}}  
      </div>
      <div class="col form-group">
          <label > Description</label><br>
          {{form.description}}  
      </div>
      <div class="col form-group">
          <label > Category</label><br>
          <select class="form-control" name="category" id="id_category">
            <option value="{{category.id}}" selected>{{category.category_name}}</option>
          </select> 
      </div>
      <div class="col form-group">
        <label > Is_featured</label><br>
        {{form.is_featured}}
      </div>
      <div class="col form-group">
         <a href=""> <input type="submit" name="submit" id="submit" class="btn btn-warning" value="Save"/></a>
      </div>
    </form>
  </div>
  
  <script>
      document.getElementById("id_sub_category_name").onkeyup=function(){
          document.getElementById("id_slug").value=document.getElementById("id_sub_category_name").value.toLowerCase().replaceAll(" ","-");
        }
  </script>
    
  {% endblock content %}

templates/adminapp/editproduct.html
{% extends 'adminapp/adminbase.html' %}
{% load static%}

{% block title%}
Edit Products
{%endblock%}

{% block navbar%}
<div class="navbar-nav w-100">
    <a href="{% url 'admin_home'%}" class="nav-item nav-link "><i class="fa fa-tachometer-alt me-2"></i>Dashboard</a>
    <a href="#" class="nav-item nav-link"><i class="fa fa-th me-2"></i>Sales Report</a>
    <a href="{% url 'products' %}" class="nav-item nav-link active"><i class="fa fa-th me-2"></i>Products</a>
    <a href="#" class="nav-item nav-link"><i class="fa fa-th me-2"></i>Categories</a>
    <a href="{% url 'user_manage'%}" class="nav-item nav-link "><i class="fa fa-keyboard me-2"></i>Users</a>
    <a href="#" class="nav-item nav-link"><i class="fa fa-table me-2"></i>Orders</a>
    <div class="nav-item dropdown">
      <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"><i class="far fa-file-alt me-2"></i>Offers</a>
      <div class="dropdown-menu bg-transparent border-0">
          <a href="#" class="dropdown-item">Category Offers</a>
          <a href="" class="dropdown-item">Product Offers</a>
          <a href="" class="dropdown-item">Coupons</a>
      </div>
  </div>
  
</div>

{%endblock%}

{% block content%}

<div class="text-center mx-auto mt-2 w-50">{% include 'includes/alerts.html' %}</div>

<div class="container mt-3" style="min-height: 33rem;">
  <h2 class="text-center text-white">Edit Product</h2>
  <form action="{% url 'editProduct' product.id %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="col form-group">
        <label > Product Name</label><br>
        {{form.product_name}}  
    </div>
    <div class="col form-group">
        <label > Slug</label><br>
        {{form.slug}}  
    </div>
    <div class="col-6 form-group">
        <label > Category</label><br>
        {{form.category}}  
    </div>
    <div class="col-6 form-group">
        <label > Sub Category</label><br>
        <select class="form-control" name="sub_category" id="id_sub_category">
          <option value="" selected="">---------</option>
        </select>  
    </div>
    <div class="col form-group">
        <label > Description</label><br>
        {{form.description}}  
    </div>
    <div class="col-3 form-group">
        <label > Price </label><br>
        {{form.price}} 
    </div>
    <div class="col-3 form-group">
        <label > Unit </label><br>
        {{form.unit}} 
    </div>
    <div class="col-3 form-group">
      <label > Stock </label><br>
      {{form.stock}}
  </div>
    <div class="col form-group">
        <label > Image 1 </label><br>
        {{form.image_1}}
    </div>
    <div class="col form-group">
        <label > Image 2 </label><br>
        {{form.image_2}}
    </div>
    <div class="col form-group">
        <label > Image 3 </label><br>
        {{form.image_3}}
    </div>
    <div class="col form-group">
        <label > Image 4 </label><br>
        {{form.image_4}}
    </div>
    <div class="col form-group">
        <label > Is Available </label><br>
        {{form.is_available}}
    </div>
    <div class="col form-group">
        <label > Is Featured </label><br>
        {{form.is_featured}}
    </div>
                     
    <div class="col form-group">
       <a href=""> <input type="submit" name="submit" id="submit" class="btn btn-warning" value="Save"/></a>
    </div>
  </form>
</div>

<script>
    document.getElementById("id_product_name").onkeyup=function(){
        document.getElementById("id_slug").value=document.getElementById("id_product_name").value.toLowerCase().replaceAll(" ","-");
      }
</script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.min.js" integrity="sha512-aVKKRRi/Q/YV+4mjoKBsE4x3H+BkegoM/em46NNlCqNTmUYADjBbeNefNxYV7giUp0VxICtqdrbqU7iVaeZNXA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script>
  function getval(sel)
  {
    var url = '{% url 'sub_category' %}'
    category_id = sel.value
      data = {
        'category_id':category_id,
    }
    $.ajax({
        url: url,
        data: data,
        dataType: 'json',
        success: function(data){
          if(data.success){
            let option_data = '<option value="" selected="">---------</option>'
            $.each(data.sub_categories, function(index, ele){
              option_data += 
                  `<option value='${ele.id}'>${ele.sub_category_name}</option>`
            })
            $('#id_sub_category').html(option_data)
            

            
          }else{
            alert('fail')
          }
        }
      })
      
  }
</script>

  
{% endblock content %}