carts/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.cart, name='cart'),
  path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
  path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name='remove_cart'),
  path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),
  
  path('checkout/', views.checkout, name='checkout'),
  
  path('decqnty/', views.decqnty, name='decqnty'),
  path('incqnty/', views.incqnty, name='incqnty'),
  
]

case/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.views.static import serve
from django.contrib import admin

urlpatterns = [
        path("admin/", admin.site.urls),

    path('', include('shop.urls')),
    path('adminn/', include('adminapp.urls')),
    path('accounts/', include('account.urls')),
    path('cart/', include('carts.urls')),
    path('orders/', include('orders.urls')),
    path('wishlist/', include('wishlist.urls')),
]

if settings.DEBUG:
    urlpatterns += [
        path('media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT}),
        path('static/<path:path>', serve, {'document_root': settings.STATIC_ROOT}),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.home, name='home'),
  path('change_password/', views.change_password, name='change_password'),
  path('forgot_password/', views.forgot_password, name='forgot_password'),
  path('verify-email/', views.verify_email, name='verify-email'),
  path('reset_password', views.reset_password, name='reset_password'),
  path('resend_otp', views.resend_otp, name='resend-otp'),


  path('shop/', views.shop, name='shop'),
  path('shop/<slug:category_slug>/', views.shop, name='products_by_category'),
  path('shop/<slug:category_slug>/<slug:sub_category_slug>/', views.shop, name='products_by_sub_category'),
  path('shop_filter/', views.shop, name='shop_filter'),
  
  path('shop/<slug:category_slug>/<slug:sub_category_slug>/<slug:product_slug>/', views.product_details, name='product_details'),
  
  path('price_change/', views.price_change, name='price_change'),
  
  path('search/', views.search, name='search'),
  path('get_product_names/', views.get_product_names, name='get_product_names'),
  path('sub_category/', views.sub_category, name='sub_category'),
  
  path('contact/', views.contact, name='contact'),
  path('save-review/<int:product_id>', views.save_review, name='save_review'),
  


   

]

category/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Category(models.Model):
  category_name = models.CharField(max_length=50, unique=True)
  slug = models.SlugField(max_length=100, unique=True)
  category_offer = models.IntegerField(default=0)
  description = models.TextField(max_length=255, blank=True)
  cat_image = models.ImageField(upload_to='photos/categories', blank=False)
  modified_at = models.DateTimeField(auto_now=True)
  
  class Meta:
        verbose_name        = 'category'
        verbose_name_plural = 'categories'

  def get_url(self):
      return reverse('products_by_category',args=[self.slug]) 
  
  def __str__(self):
    return self.category_name
  
class Sub_Category(models.Model):
  sub_category_name = models.CharField(max_length=50,unique=True)
  slug        = models.SlugField(max_length=50,unique=True)
  description      = models.TextField(max_length=300,blank=True)
  category        = models.ForeignKey(Category,on_delete=models.CASCADE)
  is_featured = models.BooleanField(default=False)
  
  class Meta:
        verbose_name        = 'sub category'
        verbose_name_plural = 'sub categories'


  def get_url(self):
        return reverse('products_by_sub_category',args=[self.category.slug, self.slug])  

  def __str__(self):
        return self.sub_category_name

shop/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from account.models import Account
from category.models import Category, Sub_Category

# Create your models here.

class Product(models.Model):
  
  UNIT = (('Piece', 'Piece'),('Combo', 'Combo'),)
  product_name = models.CharField(max_length=200, unique=True)
  slug = models.SlugField(max_length=255, unique=True)
  description = models.TextField(max_length=500, blank=True)
  price = models.IntegerField()
  product_offer = models.IntegerField(default = 0)
  unit = models.CharField(max_length=50,choices=UNIT,default='Piece')
  image_1 = models.ImageField(upload_to='photos/products', blank=False)
  image_2 = models.ImageField(upload_to='photos/products', blank=True)
  image_3 = models.ImageField(upload_to='photos/products', blank=True)
  image_4 = models.ImageField(upload_to='photos/products', blank=True)
  stock = models.IntegerField()
  is_available = models.BooleanField(default=True)
  is_featured = models.BooleanField(default=False)
  category = models.ForeignKey(Category, on_delete=models.CASCADE)
  sub_category = models.ForeignKey(Sub_Category, on_delete=models.CASCADE)
  created_date = models.DateTimeField(auto_now_add=True)
  modified_date = models.DateTimeField(auto_now=True)
  users_wishlist     =models.ManyToManyField(settings.AUTH_USER_MODEL,related_name='users_wishlist',blank=True)
  
  def get_url(self):
    return reverse('product_details', args=[self.category.slug, self.sub_category.slug, self.slug])
  
  def __str__(self):
    return self.product_name
  
  def offer_price(self):
    product_offer = int(self.price) - int(self.price) * int(self.product_offer) /100 
    category_offer = int(self.price) - int(self.price) * int(self.category.category_offer)/100
    if product_offer == int(self.price) and category_offer == int(self.price):
        return self.price
    if product_offer <= category_offer:
        return int(product_offer)
    else:
        return category_offer
  
class VariationManager(models.Manager):
  def sizes(self):
    return super(VariationManager, self).filter(variation_category='size', is_active=True)
  
variation_category_choice =  (
    ('size','size'),
)


class Variation(models.Model):
  product = models.ForeignKey(Product, on_delete=models.CASCADE)
  variation_category = models.CharField(max_length=100, choices=variation_category_choice)
  variation_value = models.CharField(max_length=100)
  is_active = models.BooleanField(default=True)
  created_date = models.DateTimeField(auto_now=True)
  
  objects = VariationManager()
  
  def __str__(self):
    return self.variation_value
  

  






#product review
RATING = (
  (1,'1'),
  (2,'2'),
  (3,'3'),
  (4,'4'),
  (5,'5'),
)
class ProductReview(models.Model):
   user = models.ForeignKey(Account, on_delete=models.CASCADE, null=True)
   product = models.ForeignKey(Product, on_delete=models.CASCADE)
   review_text = models.TextField(null=True)
   review_rating = models.CharField(choices=RATING, max_length=150)



class Banner(models.Model):
    
    banner_image =models.ImageField( upload_to='photos/banner', height_field=None, width_field=None, max_length=None,blank=True)
    
    is_selected = models.BooleanField(default=False)

shop/forms.py
from django import forms
from shop.models import Banners
from django.forms import ModelForm


class BannerForm(ModelForm):
    class Meta:
        model = Banners
        fields = ["image", "product", "alt_text"]


class EditBanner(forms.ModelForm):
    class Meta:
        model = Banners
        fields = ["image", "product", "alt_text"]

carts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse
from .models import Cart, CartItem
from orders.models import Address, Coupon, UserCoupon
from shop.models import Product, Variation
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required


# Create your views here.


def _cart_id(request):
  cart = request.session.session_key
  if not cart:
    cart = request.session.create()
  return cart



def cart(request, total=0, quantity=0, cart_items=None):
  tax=0
  grand_total=0
  product_price = 0
  
  try:
    if request.user.is_authenticated:
      cart_items = CartItem.objects.filter(user = request.user, is_active=True).order_by('id')
    else:
      cart = Cart.objects.get(cart_id=_cart_id(request))
      cart_items = CartItem.objects.filter(cart=cart, is_active=True).order_by('id')
      
    for cart_item in cart_items:
      product_price = int(cart_item.product.offer_price()) 
      total += int(cart_item.product.offer_price())*int(cart_item.quantity)
      quantity += cart_item.quantity
      cart_item.price = product_price
      cart_item.save()
    tax = (5 * total)/100
    grand_total = total + tax
    grand_total = format(grand_total, '.2f')
  except ObjectDoesNotExist:
    pass
  
  context = {
    'total':total,
    'quantity':quantity,
    'cart_items':cart_items,
    'tax':tax,
    'grand_total':grand_total,
  }
  return render(request, 'shop/cart.html', context)



def add_cart(request, product_id):
  current_user = request.user
  product = Product.objects.get(id=product_id)
  if current_user.is_authenticated:
    product_variation = []
    if request.method == 'POST':
      for item in request.POST:
        key = item
        value = request.POST[key]
        
        try:
          variation = Variation.objects.get(product=product,variation_category__iexact=key, variation_value__iexact=value)
          product_variation.append(variation)
        except:
          pass
    
    is_cart_item_exists = CartItem.objects.filter(product=product, user=current_user).exists()
    if is_cart_item_exists:
      cart_item = CartItem.objects.filter(product=product, user=current_user)
      
      ex_var_list = []
      id = []
      for item in cart_item:
        existing_variation = item.variations.all()
        ex_var_list.append(list(existing_variation))
        id.append(item.id)
      
      if product_variation in ex_var_list:
        index = ex_var_list.index(product_variation)
        item_id = id[index]
        item = CartItem.objects.get(product=product, id=item_id)
        item.quantity += 1
        item.save()
        
      else:
        item = CartItem.objects.create(product=product, quantity=1, user=current_user)
        if len(product_variation) > 0:
          item.variations.clear()
          item.variations.add(*product_variation)
          
        item.save()
    else:
      cart_item = CartItem.objects.create(
        product=product,
        quantity = 1,
        user = current_user,
      )
      if len(product_variation) > 0:
        cart_item.variations.clear()
        cart_item.variations.add(*product_variation)
      cart_item.save()
      
    return redirect('cart')
  
  # if user is not authenticated
  else:
    product_variation = []
    if request.method == 'POST':
      for item in request.POST:
        key = item
        value = request.POST[key]
        
        try:
          variation = Variation.objects.get(product=product,variation_category__iexact=key, variation_value__iexact=value)
          product_variation.append(variation)
        except:
          pass
      
    try:
      cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
      cart = Cart.objects.create(cart_id=_cart_id(request))
    
    cart.save()
    
    is_cart_item_exists = CartItem.objects.filter(product=product, cart=cart).exists()
    if is_cart_item_exists:
      cart_item = CartItem.objects.filter(product=product, cart=cart)
      
      ex_var_list = []
      id = []
      for item in cart_item:
        existing_variation = item.variations.all()
        ex_var_list.append(list(existing_variation))
        id.append(item.id)
      
      if product_variation in ex_var_list:
        index = ex_var_list.index(product_variation)
        item_id = id[index]
        item = CartItem.objects.get(product=product, id=item_id)
        item.quantity += 1
        item.save()
      else:
        item = CartItem.objects.create(product=product, quantity=1, cart=cart)
        if len(product_variation) > 0:
          item.variations.clear()
          item.variations.add(*product_variation)
          
        item.save()
    else:
      cart_item = CartItem.objects.create(
        product=product,
        quantity = 1,
        cart = cart,
      )
      if len(product_variation) > 0:
        cart_item.variations.clear()
        cart_item.variations.add(*product_variation)
      cart_item.save()
      
    return redirect('cart')



def remove_cart(request, product_id, cart_item_id):
  product = get_object_or_404(Product, id=product_id)
  
  try:
    if request.user.is_authenticated:
      cart_item = CartItem.objects.get(product=product, user=request.user, id=cart_item_id)
    else:
      cart = Cart.objects.get(cart_id=_cart_id(request))
      cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
    
    if cart_item.quantity > 1:
      cart_item.quantity  -= 1
      cart_item.save()
    else:
      cart_item.delete()
      
  except:
    pass
  return redirect('cart')



def decqnty(request):
  product_id = request.GET['pid']
  cart_item_id = request.GET['cid']
  
  product = get_object_or_404(Product, id=product_id)
  
  tax= 0
  grand_total = 0
  cart_count = 0
  try:
    if request.user.is_authenticated:
      cart_item = CartItem.objects.get(product=product, user=request.user, id=cart_item_id)
    else:
      cart = Cart.objects.get(cart_id=_cart_id(request))
      cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
    
    if cart_item.quantity > 1:
      cart_item.quantity  -= 1
      cart_item.save()
    else:
      cart_item.delete()
      
    sub_total = cart_item.sub_total()
        
  except:
    pass
  
  try:
    if request.user.is_authenticated:
      cart_items = CartItem.objects.filter(user = request.user, is_active=True)
    else:
      cart = Cart.objects.get(cart_id=_cart_id(request))
      cart_items = CartItem.objects.filter(cart=cart, is_active=True)
    
    for cart_item in cart_items:
      cart_count += cart_item.quantity
        
    total = 0
    for cart_item in cart_items:
      total += int(cart_item.price)*int(cart_item.quantity)
    
    print(total)
    tax = (5 * total)/100
    grand_total = total + tax
    grand_total = format(grand_total, '.2f')

  except:
    pass
  
  return JsonResponse(
          {'success': True,
           'qnty':cart_item.quantity,
           'sub_total':sub_total,
           'cart_count':cart_count,
           'total':total,
           'tax':tax,
           'grand_total':grand_total,
           },
          safe=False
        )

 
  
def incqnty(request):
  if request.method == 'POST':
    product_id = request.POST['pid']
    cart_item_id = request.POST['cid']
  
  product = get_object_or_404(Product, id=product_id)
  
  tax= 0
  grand_total = 0
  cart_count = 0
  try:
    if request.user.is_authenticated:
      cart_item = CartItem.objects.get(product=product, user=request.user, id=cart_item_id)
    else:
      cart = Cart.objects.get(cart_id=_cart_id(request))
      cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
    
    if cart_item.quantity < cart_item.product.stock:
      cart_item.quantity  += 1
      cart_item.save()
      
    sub_total = cart_item.sub_total()
        
  except:
    pass
  
  try:
    if request.user.is_authenticated:
      cart_items = CartItem.objects.filter(user = request.user, is_active=True)
    else:
      cart = Cart.objects.get(cart_id=_cart_id(request))
      cart_items = CartItem.objects.filter(cart=cart, is_active=True)
      
    for cart_item in cart_items:
      cart_count += cart_item.quantity
        
    total = 0
    
    for cart_item in cart_items:
      total += int(cart_item.price)*int(cart_item.quantity)
       
    tax = (5 * total)/100
    grand_total = total + tax
    grand_total = format(grand_total, '.2f')

  except:
    pass
  
  return JsonResponse(
          {'success': True,
           'qnty':cart_item.quantity,
           'sub_total':sub_total,
           'cart_count':cart_count,
           'total':total,
           'tax':tax,
           'grand_total':grand_total,
           },
          safe=False
        )

def remove_cart_item(request, product_id, cart_item_id):
  product = get_object_or_404(Product, id=product_id)
  
  if request.user.is_authenticated:
    cart_item = CartItem.objects.get(product=product, user=request.user, id=cart_item_id)
  else:
    cart = Cart.objects.get(cart_id=_cart_id(request))
    cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
  cart_item.delete()
  return redirect('cart')

@login_required(login_url = 'userLogin')
def checkout(request, total=0, quantity=0, cart_items=None):
  tax=0
  grand_total=0
  address = Address.objects.filter(user = request.user)
  
  try:
    if request.user.is_authenticated:
      cart_items = CartItem.objects.filter(user = request.user, is_active=True)
    else:
      cart = Cart.objects.get(cart_id=_cart_id(request))
      cart_items = CartItem.objects.filter(cart=cart, is_active=True)

    for cart_item in cart_items:
      total += int(cart_item.price)*int(cart_item.quantity)
      quantity += cart_item.quantity
    tax = (5 * total)/100
    grand_total = total + tax
    grand_total = format(grand_total, '.2f')
  except ObjectDoesNotExist:
    pass
  

templates/shop/shop.html
{% extends 'userapp/base.html' %}
{% load static%}

{% block title%}
Shop
{%endblock%}

{% block content%}

<section class="page-add">
    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                <div class="page-breadcrumb">
                    <h2>Cases<span>.</span></h2>
                    <a href="{% url 'home' %}">Home</a>
                    <a class="active" href="#">All Cases</a>
                </div>
            </div>
        </div>
    </div>
</section>

  <!-- Product Section Begin -->
<section class="product spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-5">
                <div class="sidebar">
                    <div class="sidebar__item ">
                        <h4>Filter By Category</h4>
                        <ul class="overflow-auto"  style="max-height: 29rem;">
                          <li style="list-style:none;"><a class="text-dark f-5" href="{% url 'shop' %}">
                              All Products
                          </a></li>
                          {% for category in cat_links %}
                          {% for i in category.sub_category_set.all %}
                          <li style="list-style:none;"><a class="text-dark f-5"  href="{{i.get_url}}">
                            {{i.sub_category_name}}
                          </a></li>
                        {% endfor %}
                        {% endfor %}

                          {% for i in variation_set.all %}
                          <li style="list-style:none;"><a class="text-dark f-5"  href="">
                            {{i.variation_value}}
                          </a></li>
                        {% endfor %}
                      
                        </ul>
                    </div>
                    
                </div>
            </div>
            
            <div class="col-lg-9 col-md-7">
  
                <div class="filter__item">
                    <div class="row">
                        <div class="col-lg-4 col-md-5">
                        </div>
                        <div class="col-lg-4 col-md-4">
                            <div class="filter__found">
                                {% comment %} <h6><span>{{product_count}}</span> Products found</h6> {% endcomment %}
                            </div>
                        </div>
                       
                    </div>
                </div>
                <div class="row">
  
                  {% for product in products  %}
  
                  <div class="col-lg-4 col-md-6 col-sm-6">
                    <div class="single-product-item">
                        <a href="{{product.get_url}}">
                            <figure>
                                <img src="{{product.image_1.url}}" alt="">
                                <div class="p-status">new</div>
                            </figure></a> 
                            <div class="product-text">
                                <a href="{{product.get_url}}">
                                    <h6 style="">{{product.product_name}}</h6>
                                </a>
                               
                                {% if product.offer_price != product.price %}
                                <p><del class="text-secondary">₹{{product.price}}</del> ₹{{product.offer_price}}</p>
                                {% else %}
                                <p>₹{{product.price}}</p>
                                {% endif %}
                            </div>
                    </div>
                  </div>
                  
                  {% endfor %}
  
                </div>
                
                <div class="product__pagination">
                  {% if products.has_previous %}
                    <a href="?page={{ products.previous_page_number }}"><i class="fa fa-long-arrow-left"></i></a>
                  {% endif %}
                    <a href="?page={{ products.number }}">{{ products.number }}</a>
                  {% if products.has_next %}
                    <a href="?page={{ products.next_page_number }}">{{ products.next_page_number }}</a>
                  {%endif%}
  
                  {% if products.has_next %}
                    <a href="?page={{ products.next_page_number }}"><i class="fa fa-long-arrow-right"></i></a>
                  {%endif%}
                </div>
  
            </div>
        </div>
    </div>
  </section>
  <!-- Product Section End -->

   


{%endblock content%}